# Generated by Django 4.2.23 on 2025-08-22 19:41

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        choices=[
                            ("Table", "Table"),
                            ("Chaise", "Chaise"),
                            ("Armoire", "Armoire"),
                            ("Étagère", "Étagère"),
                            ("Bureau", "Bureau"),
                            ("Lit", "Lit"),
                            ("Commode", "Commode"),
                            ("Canapé", "Canapé"),
                            ("Meuble TV", "Meuble TV"),
                            ("Bibliothèque", "Bibliothèque"),
                        ],
                        max_length=100,
                        verbose_name="Nom de l'article",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Chêne", "Chêne"),
                            ("Sapin", "Sapin"),
                            ("Iroko", "Iroko"),
                            ("Érable", "Érable"),
                            ("Acajou", "Acajou"),
                            ("Hêtre", "Hêtre"),
                            ("Bouleau", "Bouleau"),
                            ("Meranti", "Meranti"),
                            ("Teck", "Teck"),
                            ("Pin", "Pin"),
                        ],
                        max_length=50,
                        verbose_name="Type de bois",
                    ),
                ),
                (
                    "epaisseur",
                    models.DecimalField(
                        choices=[
                            (Decimal("5.0"), "5"),
                            (Decimal("10.0"), "10"),
                            (Decimal("15.0"), "15"),
                            (Decimal("20.0"), "20"),
                            (Decimal("25.0"), "25"),
                            (Decimal("30.0"), "30"),
                        ],
                        decimal_places=2,
                        default=Decimal("5.0"),
                        max_digits=6,
                        verbose_name="Épaisseur (mm)",
                    ),
                ),
                (
                    "prix_payer",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="prix_payer (MAD)",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("adresse", models.CharField(default="", max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telephone", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Planche",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("longueur_initiale_mm", models.IntegerField()),
                ("largeur_initiale_mm", models.IntegerField()),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planches",
                        to="api.article",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Piece",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("longueur_desiree_mm", models.IntegerField()),
                ("largeur_desiree_mm", models.IntegerField()),
                ("quantite", models.IntegerField(default=1)),
                (
                    "planche",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pieces",
                        to="api.planche",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mesure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "longueur",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Longueur (cm)"
                    ),
                ),
                (
                    "largeur",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Largeur (cm)"
                    ),
                ),
                (
                    "nombre_de_fois",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Nombre de fois"
                    ),
                ),
                ("encadrement_droite", models.BooleanField(default=False)),
                ("encadrement_gauche", models.BooleanField(default=False)),
                ("encadrement_haut", models.BooleanField(default=False)),
                ("encadrement_bas", models.BooleanField(default=False)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mesures",
                        to="api.article",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.client"
            ),
        ),
    ]
