# Generated by Django 4.2.23 on 2025-08-22 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20250822_2049"),
    ]

    operations = []
