# Generated by Django 4.2.23 on 2025-08-24 10:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_auto_20250822_2055"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="prix_payer",
        ),
        migrations.AddField(
            model_name="article",
            name="prix_restant",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Prix restant (DH)",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="prix_total",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Prix total (DH)",
            ),
        ),
    ]
