# Generated by Django 4.2.23 on 2025-09-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_article_date_creation_article_date_modification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="valide",
            field=models.BooleanField(default=True),
        ),
    ]
