# Generated by Django 4.2.23 on 2025-09-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_article_valide"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="valide",
            field=models.BooleanField(default=False),
        ),
    ]
