# Generated by Django 4.2.23 on 2025-09-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_article_valide"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="schema",
            field=models.TextField(blank=True, null=True, verbose_name="Schéma SVG"),
        ),
    ]
