from django.urls import path
from . import views

urlpatterns = [
    path('hello/', views.hello, name='hello'),
    path('inscription_client/', views.inscription_client, name='inscription_client'),
    path('login/', views.login, name='login'),
    path('liste_clients/', views.liste_clients, name='liste_clients'),
    path('client_info/', views.get_client_par_username, name='client_info'),
    path('articles_statistiques', views.statistiques_articles, name='statistiques_articles'),
    path('liste_articles', views.liste_articles, name='liste_articles'),
    path('supprimer_article_client/<int:article_id>', views.supprimer_article_client, name='supprimer_article_client'),
    path('supprimer_mesure_client/<int:mesure_id>', views.supprimer_mesure_client, name='supprimer_mesure_client'),
    path('modifier_article_client/<int:article_id>', views.modifier_article_client, name='modifier_article_client'),
    path('modifier_mesure_client/<int:mesure_id>', views.modifier_mesure_client, name='modifier_mesure_client'),
    path('statistiques_articles_client', views.statistiques_articles_client, name='statistiques_articles_client'),
    path('ajouter_client_client', views.ajouter_client_client, name='ajouter_client_client'),
    path('ajouter_client', views.ajouter_client, name='ajouter_client'),
    path('ajouter_article_client', views.ajouter_article_client, name='ajouter_article_client'),
    path('liste_articles_client', views.liste_articles_client, name='liste_articles_client'),
    path('liste_articles_clients', views.liste_articles_clients, name='liste_articles_clients'),
    path('liste_articles_valideur', views.liste_articles_valideur, name='liste_articles_valideur'),
    path('modifier_client/<int:client_id>/', views.modifier_client, name='modifier_client'),
    path('supprimer_client/<int:client_id>/', views.supprimer_client, name='supprimer_client'),
    path('ajouter_article', views.ajouter_article, name='ajouter_article'),
    path('modifier_article/<int:article_id>', views.modifier_article, name='modifier_article'),
    path('supprimer_article/<int:article_id>', views.supprimer_article, name='supprimer_article'),
    path('supprimer_mesure_client/<int:mesure_id>/', views.supprimer_mesure, name='supprimer_mesure_client'),
    path("articles/<int:article_id>/mesures/", views.liste_mesures_article, name="liste_mesures_article"),
    path("exporter_articles_csv/<int:article_id>/", views.exporter_articles_csv, name="exporter_articles_csv"),
    path("exporter_articles_text/<int:article_id>/", views.exporter_articles_text, name="exporter_articles_text"),
    path('prix_total_detail/<int:article_id>/', views.prix_total_detail, name='prix_total_detail'),
    path("paiement/<int:article_id>/", views.paiement, name="paiement"),
    path('changer_prix_article/<int:article_id>/', views.changer_prix_article, name='changer_prix_article'),
    path('valider_mesure/<int:article_id>/', views.valider_mesure, name='valider_mesure'),
    path('ajouter_mesure_client/<int:article_id>/', views.ajouter_mesure, name='ajouter_mesure'),
    path('optimisation_decoupage/<int:article_id>/', views.optimisation_decoupage, name='optimisation_decoupage'),
    path('valider_decouppage_valideur/<int:article_id>/', views.valider_decouppage_valideur, name='valider_decouppage_valideur'),
    path('liste_article_valideur/<int:article_id>/', views.liste_article_valideur, name='liste_article_valideur'),
    path('marquer_article_valide/<int:article_id>/', views.marquer_article_valide, name='marquer_article_valide'),
    path("schema_pdf/<int:article_id>/", views.schema_pdf, name="schema_pdf"),
    path('valider_decouppage/<int:article_id>/', views.valider_decouppage, name='valider_decouppage'),
    path('total_mesures', views.afficher_total_mesures, name='afficher_total_mesures'),
    path('prix_planche/<int:article_id>/', views.prix_planche, name='prix_planche'),
]